import { Piece, Shade } from '../models/enums'
export const InitialPosition = [
    {
        id: 'black-rook-1-8',
        name: Piece.ROOK,
        x: 'a',
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-knight-2-8',
        name: Piece.KNIGHT,
        x: 2,
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-bishop-3-8',
        name: Piece.BISHOP,
        x: 3,
        y: 8,
        color: Shade.Dark,
    },
{
        id: 'black-queen-4-8',
        name: Piece.QUEEN,
        x: 4,
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-king-5-8',
        name: Piece.KING,
        x: 5,
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-bishop-6-8',
        name: Piece.BISHOP,
        x: 6,
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-knight-7-8',
        name: Piece.KNIGHT,
        x: 7,
        y: 8,
        color: Shade.Dark,
    },
    {
        id: 'black-rook-8-8',
        name: Piece.ROOK,
        x: 8,
        y: 8,
        color: Shade.Dark,
    },


    {
        id: 'black-pawn-1-7',
        name: Piece.PAWN,
        y: 7,
        x: 'a',
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-2-7',
        name: Piece.PAWN,
        y: 7,
        x: 2,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-3-7',
        name: Piece.PAWN,
        y: 7,
        x: 3,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-4-7',
        name: Piece.PAWN,
        y: 7,
        x: 4,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-5-7',
        name: Piece.PAWN,
        y: 7,
        x: 5,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-6-7',
        name: Piece.PAWN,
        y: 7,
        x: 6,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-7-7',
        name: Piece.PAWN,
        y: 7,
        x: 7,
        color: Shade.Dark,
    },
    {
        id: 'black-pawn-8-7',
        name: Piece.PAWN,
        y: 7,
        x: 8,
        color: Shade.Dark,
    },

    {
        id: 'white-rook-1-1',
        name: Piece.ROOK,
        x: 'a',
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-knight-2-1',
        name: Piece.KNIGHT,
        x: 2,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-bishop-3-1',
        name: Piece.BISHOP,
        x: 3,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-queen-4-1',
        name: Piece.QUEEN,
        x: 4,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-king-5-1',
        name: Piece.KING,
        x: 5,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-bishop-6-1',
        name: Piece.BISHOP,
        x: 6,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-knight-7-1',
        name: Piece.KNIGHT,
        x: 7,
        y: 1,
        color: Shade.Light,
    },
    {
        id: 'white-rook-8-1',
        name: Piece.ROOK,
        x: 8,
        y: 1,
        color: Shade.Light,
    },


    {
        id: 'white-pawn-1-2',
        name: Piece.PAWN,
        y: 2,
        x: 'a',
        color: Shade.Light,
    },
    {
        id: 'white-pawn-2-2',
        name: Piece.PAWN,
        y: 2,
        x: 2,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-3-2',
        name: Piece.PAWN,
        y: 2,
        x: 3,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-4-2',
        name: Piece.PAWN,
        y: 2,
        x: 4,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-5-2',
        name: Piece.PAWN,
        y: 2,
        x: 5,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-6-2',
        name: Piece.PAWN,
        y: 2,
        x: 6,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-7-2',
        name: Piece.PAWN,
        y: 2,
        x: 7,
        color: Shade.Light,
    },
    {
        id: 'white-pawn-8-2',
        name: Piece.PAWN,
        y: 2,
        x: 8,
        color: Shade.Light,
    }
]